export const cutoffData = [
  {
    courseName: 'B.Tech',
    courseFullname: 'B.Tech in Computer Engineering',
    scNeutral: 202,
    stFemale: 54,
    stNeutral: 83,
    genFemale: 0,
    genNeutral: 0,
    genPwd: 0,
    obcFemale: 0,
    obcNeutral: 0,
  },
  {
    courseName: 'B.Tech',
    courseFullname: 'B.Tech in Computer Engineering',
    scNeutral: 202,
    stFemale: 54,
    stNeutral: 83,
    genFemale: 0,
    genNeutral: 0,
    genPwd: 0,
    obcFemale: 0,
    obcNeutral: 0,
  },
  {
    courseName: 'B.Tech',
    courseFullname: 'B.Tech in Computer Engineering',
    scNeutral: 202,
    stFemale: 54,
    stNeutral: 83,
    genFemale: 0,
    genNeutral: 0,
    genPwd: 0,
    obcFemale: 0,
    obcNeutral: 0,
  },
  {
    courseName: 'B.Tech',
    courseFullname: 'B.Tech in Computer Engineering',
    scNeutral: 202,
    stFemale: 54,
    stNeutral: 83,
    genFemale: 0,
    genNeutral: 0,
    genPwd: 0,
    obcFemale: 0,
    obcNeutral: 0,
  },
  {
    courseName: 'B.Tech',
    courseFullname: 'B.Tech in Computer Engineering',
    scNeutral: 202,
    stFemale: 54,
    stNeutral: 83,
    genFemale: 0,
    genNeutral: 0,
    genPwd: 0,
    obcFemale: 0,
    obcNeutral: 0,
  },
  {
    courseName: 'B.Tech',
    courseFullname: 'B.Tech in Computer Engineering',
    scNeutral: 202,
    stFemale: 54,
    stNeutral: 83,
    genFemale: 0,
    genNeutral: 0,
    genPwd: 0,
    obcFemale: 0,
    obcNeutral: 0,
  },
];
