export const categories = ['Engineering', 'Management', 'Medical', 'Information and technology'];

export const enggData = {
  colleges: [
    'Parul University',
    'Chandigarh University',
    'K. R. Mangalam University',
    'Swarnim Startup and Innovation University',
    'Lovely Professional University',
    'Sanskriti University',
    'Jaipur National University',
    'Institute of Engineering and Management',
  ],
  exams: ['JEE Main', 'JEE Advanced', 'TS EAMCET', 'WBJEE', 'VITEEE'],
  states: ['Maharashtra', 'Tamilnadu', 'Uttar Pradesh', 'Karnataka', 'Rajasthan', 'Punjab'],
  courses: [
    'B Tech',
    'M Tech',
    'Bachelor of Engineering',
    'Civil Engineering',
    'Mechanical Engineering',
    'Automobile Engineering',
    'Aerospace Engineering',
    'Aeronautical Engineering',
    'Software Engineering',
    'Computer Engineering',
  ],
};

export const managementData = {
  colleges: [
    'Parul University',
    'Chandigarh University',
    'K. R. Mangalam University',
    'Swarnim Startup and Innovation University',
    'Lovely Professional University',
    'Sanskriti University',
    'Jaipur National University',
    'Institute of Engineering and Management',
  ],
  exams: ['CAT', 'XAT', 'CMAT', 'NMAT', 'SNA'],
  states: ['Maharashtra', 'Tamilnadu', 'Delhi', 'Karnataka', 'Rajasthan', 'Punjab'],
  courses: [
    'MBA',
    'BBA',
    'BBA+MBA',
    'MBA in Finance',
    'BBM',
    'Executive MBA',
    'PGDM',
    'MBA in HR',
    'MBA in Event Management',
    'MBA in Marketing',
  ],
};

export const medicalData = {
  colleges: [
    '    Parul University',
    'Dev Bhoomi Uttarakhand University',
    'Swarnim Startup and Innovation University',
    'Lovely Professional University',
    'Chandigarh University',
    'Marudhar Engineering College',
    'Abes Engineering College',
    'Kongunadu Arts & Science College',
    'Shanti Business School',
    'I.T.S. Dental College, Muradnagar',
  ],
  exams: ['NEET', 'NEET PG', ' NEET SS', ' INI CET', 'FMGE'],
  states: ['Maharashtra', 'Tamilnadu', 'Delhi', 'Karnataka', 'Rajasthan'],
  courses: [
    'MBBS',
    'BPT',
    'Doctorate of Medicine',
    'Doctor of Medicine',
    'BHMS',
    'BAMS',
    'DMLT Course',
    'MLT',
    'BUMS',
    'Masters of Public Health',
  ],
};

export const ITData = {
  colleges: [
    '    Parul University',
    'Dev Bhoomi Uttarakhand University',
    'Swarnim Startup and Innovation University',
    'Lovely Professional University',
    'Chandigarh University',
    'Marudhar Engineering College',
    'Abes Engineering College',
    'Kongunadu Arts & Science College',
    'Shanti Business School',
    'I.T.S. Dental College, Muradnagar',
  ],
  exams: ['OJEE', 'KIITEE', 'JNUEE', 'UPSEE', 'CUSAT CAT'],
  states: [
    'Maharashtra',
    'Tamilnadu',
    'Uttar Pradesh',
    'Delhi',
    'Karnataka',
    'Rajasthan',
    'Punjab',
  ],
  courses: [
    'BCA',
    'MCA',
    'DCA',
    '  MSc Data Science',
    ' PGDCA Course',
    ' BBA in Computer Application',
    '  B Sc IT',
    ' MSc IT',
    ' B Tech IT',
    ' M Tech IT',
  ],
};
