export const colleges = [
  {
    logo: '/assets/college/college__logo.png',
    img: '/assets/college/college_1.png',
    name: 'Indian Institute of Technology, Madras',
    location: 'Madras, India',
    fees: '20K - 3.17 L',
    exam: 'JEE Adv',
    package: '12.4 Lacs',
    affiliation: 'AICTE',
    about:
      'IT Madras B.Tech, BS + MS and B.Tech+M.Tech admission is based on JEE Advanced and JEE Main. The college offers 92 courses at the PG and UG levels. For admission to the MBA, CAT...',
    rating: 4.8,
  },
  {
    logo: '/assets/college/college__logo.png',
    img: '/assets/college/college_1.png',
    name: 'Indian Institute of Technology, Madras',
    location: 'Madras, India',
    fees: '20K - 3.17 L',
    exam: 'JEE Adv',
    package: '12.4 Lacs',
    affiliation: 'AICTE',
    about:
      'IT Madras B.Tech, BS + MS and B.Tech+M.Tech admission is based on JEE Advanced and JEE Main. The college offers 92 courses at the PG and UG levels. For admission to the MBA, CAT...',
    rating: 4.8,
  },
  {
    logo: '/assets/college/college__logo.png',
    img: '/assets/college/college_1.png',
    name: 'Indian Institute of Technology, Madras',
    location: 'Madras, India',
    fees: '20K - 3.17 L',
    exam: 'JEE Adv',
    package: '12.4 Lacs',
    affiliation: 'AICTE',
    about:
      'IT Madras B.Tech, BS + MS and B.Tech+M.Tech admission is based on JEE Advanced and JEE Main. The college offers 92 courses at the PG and UG levels. For admission to the MBA, CAT...',
    rating: 4.8,
  },
  {
    logo: '/assets/college/college__logo.png',
    img: '/assets/college/college_1.png',
    name: 'Indian Institute of Technology, Delhi',
    location: 'Madras, India',
    fees: '20K - 3.17 L',
    exam: 'JEE Adv',
    package: '12.4 Lacs',
    affiliation: 'AICTE',
    about:
      'IT Madras B.Tech, BS + MS and B.Tech+M.Tech admission is based on JEE Advanced and JEE Main. The college offers 92 courses at the PG and UG levels. For admission to the MBA, CAT...',
    rating: 4.8,
  },
  {
    logo: '/assets/college/college__logo.png',
    img: '/assets/college/college_1.png',
    name: 'Indian Institute of Technology, Delhi',
    location: 'Madras, India',
    fees: '20K - 3.17 L',
    exam: 'JEE Adv',
    package: '12.4 Lacs',
    affiliation: 'AICTE',
    about:
      'IT Madras B.Tech, BS + MS and B.Tech+M.Tech admission is based on JEE Advanced and JEE Main. The college offers 92 courses at the PG and UG levels. For admission to the MBA, CAT...',
    rating: 4.8,
  },
  {
    logo: '/assets/college/college__logo.png',
    img: '/assets/college/college_1.png',
    name: 'Indian Institute of Technology, Delhi',
    location: 'Madras, India',
    fees: '20K - 3.17 L',
    exam: 'JEE Adv',
    package: '12.4 Lacs',
    affiliation: 'AICTE',
    about:
      'IT Madras B.Tech, BS + MS and B.Tech+M.Tech admission is based on JEE Advanced and JEE Main. The college offers 92 courses at the PG and UG levels. For admission to the MBA, CAT...',
    rating: 4.8,
  },
];
